name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {BADGE: bionic,
             OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             ROS_REPO: main,
             ADDITIONAL_DEBS: git,
             VERBOSE_TESTS: true,
             TARGET_CMAKE_ARGS: "-DRCT_BUILD_TESTS=ON",
             CTEST_OUTPUT_ON_FAILURE: true,
             AFTER_SCRIPT: "cd $target_ws/build/rct_optimizations && ctest -V && cd $target_ws/build/rct_image_tools && ctest -V"}
          - {BADGE: xenial,
             OS_NAME: ubuntu,
             OS_CODE_NAME: xenial,
             ROS_DISTRO: kinetic,
             ROS_REPO: main,
             ADDITIONAL_DEBS: git,
             VERBOSE_TESTS: true,
             TARGET_CMAKE_ARGS: "-DRCT_BUILD_TESTS=ON",
             CTEST_OUTPUT_ON_FAILURE: true,
             AFTER_SCRIPT: 'cd $target_ws/build/rct_optimizations && ctest -V && cd $target_ws/build/rct_image_tools && ctest -V'}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
