name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        distro: [melodic, noetic]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          BADGE: ${{ matrix.distro }}
          ROS_DISTRO: ${{ matrix.distro }}
          ROS_REPO: main
          VERBOSE_TESTS: true
          TARGET_CMAKE_ARGS: "-DRCT_BUILD_TESTS=ON"
          CTEST_OUTPUT_ON_FAILURE: true
          AFTER_SCRIPT: "cd $target_ws/build/rct_optimizations && ctest -V && cd $target_ws/build/rct_image_tools && ctest -V"
